### PR TITLE
Update jQuery Mobile, fixes issue #72

### PR DESCRIPTION
**Pull request by gsantner**
Update jQuery Mobile, fixes issue #72 with white page

### CODE REVIEW

**Comment by gsantner** [comment]
I'm closing this PR as no response and project unmaintained. I'm fine with having a own project and not contribute upstream as I see there's no interest.

**Comment by nodiscc** [comment]
@gsantner you could ask @mboinet to give you ownership of the repo if you intend to maintain it? I no longer use it but found it useful in the past. Good luck

**Comment by mboinet** [comment]
Hello. Yes, I totally can give you ownership.

**Comment by gsantner** [comment]
To be honest I didn't expect any response :D. Currently I removed the fork-relationship and placed stuff here <https://github.com/gsantner/ttrss-reader-mobile-html5-webapp>.

@mboinet Thanks for your existing work and interest to keep it up. What do you mean by ownership? As in, "transfer" the repo with the existing issues/feature requests to `gsantner/ttrss-reader-mobile-html5-webapp`?

**Comment by mboinet** [comment]
From what I could see, it's at least possible to transfer ownership or give you rights on the repo. What would work better for you?

**Comment by gsantner** [comment]
I dont have much of a preference. I did quite some improvements so it works good for me and I want others to get the improvements.

**Pull request closed without merging**
